runtime: php55
api_version: 1

runtime_config:
  document_root: ShopBook

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

- url: /
  script: index.php
# - url: /ctroller
#   script: ctr_book.php

- url: /stylesheets
  static_dir: stylesheets